{
 "title": "IDS-POC",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total bytes processed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ids_total_bytes_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total packets analyzed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ids_packets_analyzed_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "IDS Alerts",
   "type": "piechart",
   "description": "Total IDS alerts by attack type",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ids_alerts_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of unique source IPs",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ids_unique_ips", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current active connections",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "current_active_connections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total UDP Flood attacks",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_udp_flood_attacks_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total detected DDoS attacks",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "total_detected_ddos_attacks_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total TCP SYN Flood attacks",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "total_tcp_syn_flood_attacks_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Port Scan alerts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ids_alerts_total{type=\"PortScan\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}